// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDHVZNFW-oAmbqU4Zhj-eKImu-RM_12IM',
    appId: '1:56411460300:web:7bcd5218810c1e091be869',
    messagingSenderId: '56411460300',
    projectId: 'task6-2b559',
    authDomain: 'task6-2b559.firebaseapp.com',
    storageBucket: 'task6-2b559.firebasestorage.app',
    measurementId: 'G-L5KXCXD6C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5GTUeyPP35qrwEBJxOvCXfACxaqHd15g',
    appId: '1:56411460300:android:658189bd676420091be869',
    messagingSenderId: '56411460300',
    projectId: 'task6-2b559',
    storageBucket: 'task6-2b559.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD96hLslH6FrPLwDX0QA4_av7TC9BUXfzo',
    appId: '1:56411460300:ios:f360269f47ebe3da1be869',
    messagingSenderId: '56411460300',
    projectId: 'task6-2b559',
    storageBucket: 'task6-2b559.firebasestorage.app',
    iosBundleId: 'com.example.task6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD96hLslH6FrPLwDX0QA4_av7TC9BUXfzo',
    appId: '1:56411460300:ios:f360269f47ebe3da1be869',
    messagingSenderId: '56411460300',
    projectId: 'task6-2b559',
    storageBucket: 'task6-2b559.firebasestorage.app',
    iosBundleId: 'com.example.task6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDHVZNFW-oAmbqU4Zhj-eKImu-RM_12IM',
    appId: '1:56411460300:web:516150ab1bd3f0991be869',
    messagingSenderId: '56411460300',
    projectId: 'task6-2b559',
    authDomain: 'task6-2b559.firebaseapp.com',
    storageBucket: 'task6-2b559.firebasestorage.app',
    measurementId: 'G-BP6QTJWH8L',
  );
}
